### ISSUE TITLE
Add `pretty` query string parameter

### ISSUE THREAD

**Issue by breml** [floragunncom/search-guard-rest-api#10]
The REST API in Elasticsearch allows to provide the `pretty` query string parameter, which causes the JSON response to be nicely formatted, which makes it much easier to read the output as a human. Please add this query string parameter to the Search-Guard REST API as well to allow for a consistent user experience.

**Comment by floragunncom** [comment]
This is already known and will be released with the next version

**Comment by floragunncom** [comment]
released with v24.1
